#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f ".nvmrc" ] && [ -z "$(which nvm 2>/dev/null)" ]; then
  echo "==> Installing Node and NPM..."
  nvm use
fi

if [ -f "package.json" ]; then
  echo "==> Installing NPM dependencies..."
  npm install
fi

if [ -f "bower.json" ]; then
  echo "==> Installing Bower dependencies..."
  npm run bower
fi
